# Generated by Django 3.2.23 on 2024-02-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveInDrugMissedAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=150)),
                ('district', models.CharField(blank=True, max_length=150, null=True)),
                ('health_facility', models.CharField(blank=True, max_length=150, null=True)),
                ('patient_name', models.CharField(blank=True, max_length=255, null=True)),
                ('patient_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.IntegerField()),
                ('phone_number', models.CharField(blank=True, max_length=150, null=True)),
                ('appointment_date', models.DateTimeField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=150, null=True)),
                ('pregnant', models.CharField(blank=True, default='NAO', max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Active in Drug Missed Appointment',
                'verbose_name_plural': 'Active in Drug Missed Appointments',
            },
        ),
    ]
