# Generated by Django 3.2.19 on 2023-05-26 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ElegiveisCv',
        ),
        migrations.DeleteModel(
            name='MarcadosLevantamento',
        ),
        migrations.DeleteModel(
            name='PacientesCargaAlta',
        ),
        migrations.RenameField(
            model_name='missedappointment',
            old_name='synced',
            new_name='sent',
        ),
        migrations.RenameField(
            model_name='patienteligiblevlcollection',
            old_name='synced',
            new_name='sent',
        ),
        migrations.RenameField(
            model_name='viralloadtestresult',
            old_name='synced',
            new_name='sent',
        ),
        migrations.RenameField(
            model_name='visit',
            old_name='synced',
            new_name='sent',
        ),
    ]
