# Generated by Django 3.2.19 on 2023-05-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=100)),
                ('openmrs_username', models.CharField(max_length=100)),
                ('openmrs_password', models.CharField(max_length=100)),
                ('openmrs_url', models.CharField(max_length=100)),
                ('openmrs_rest_endpoint', models.CharField(max_length=100)),
                ('reminder_uuid', models.CharField(max_length=100)),
                ('missed_appointment_uuid', models.CharField(max_length=100)),
                ('viral_load_eligibility_uuid', models.CharField(max_length=100)),
                ('viral_load_test_result_uuid', models.CharField(max_length=100)),
                ('viamo_api_url', models.CharField(max_length=100)),
                ('viamo_api_public_key', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=100)),
                ('property_value', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Global Properties',
            },
        ),
        migrations.CreateModel(
            name='MissedAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=150)),
                ('district', models.CharField(blank=True, max_length=150, null=True)),
                ('health_facility', models.CharField(blank=True, max_length=150, null=True)),
                ('patient_id', models.IntegerField()),
                ('patient_name', models.CharField(max_length=255)),
                ('patient_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.IntegerField()),
                ('phone_number', models.CharField(blank=True, max_length=150, null=True)),
                ('last_appointment_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=150, null=True)),
                ('community', models.CharField(blank=True, max_length=500, null=True)),
                ('pregnant', models.CharField(blank=True, default='NAO', max_length=10, null=True)),
                ('drug_pickup_missed_days', models.IntegerField(blank=True, default=0, null=True)),
                ('visit_missed_days', models.IntegerField(blank=True, default=0, null=True)),
                ('synced', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PatientEligibleVLCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=150)),
                ('district', models.CharField(blank=True, max_length=150, null=True)),
                ('community', models.CharField(blank=True, max_length=150, null=True)),
                ('health_facility', models.CharField(blank=True, max_length=150, null=True)),
                ('patient_id', models.IntegerField()),
                ('patient_name', models.CharField(max_length=255)),
                ('patient_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.IntegerField()),
                ('phone_number', models.CharField(blank=True, max_length=150, null=True)),
                ('pregnant', models.CharField(blank=True, default='NAO', max_length=10, null=True)),
                ('last_vl_date', models.DateTimeField(blank=True, null=True)),
                ('last_vl_value', models.CharField(blank=True, max_length=100, null=True)),
                ('last_vl_quality', models.CharField(blank=True, max_length=100, null=True)),
                ('synced', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Patient Eligible for VL Collection',
                'verbose_name_plural': 'Patients Eligible for VL Collection',
            },
        ),
        migrations.CreateModel(
            name='ViralLoadTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=150)),
                ('district', models.CharField(blank=True, max_length=150, null=True)),
                ('community', models.CharField(blank=True, max_length=150, null=True)),
                ('health_facility', models.CharField(blank=True, max_length=150, null=True)),
                ('patient_id', models.IntegerField()),
                ('patient_name', models.CharField(max_length=255)),
                ('patient_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.IntegerField()),
                ('phone_number', models.CharField(blank=True, max_length=150, null=True)),
                ('pregnant', models.CharField(blank=True, default='NAO', max_length=10, null=True)),
                ('last_vl_date', models.DateTimeField(blank=True, null=True)),
                ('last_vl_value', models.CharField(blank=True, max_length=100, null=True)),
                ('last_vl_quality', models.CharField(blank=True, max_length=100, null=True)),
                ('synced', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Viral Load Test Result',
                'verbose_name_plural': 'Viral Load Test Results',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=150)),
                ('district', models.CharField(blank=True, max_length=150, null=True)),
                ('health_facility', models.CharField(max_length=150)),
                ('patient_id', models.IntegerField()),
                ('patient_name', models.CharField(max_length=255)),
                ('patient_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.IntegerField()),
                ('phone_number', models.CharField(blank=True, max_length=150, null=True)),
                ('appointment_date', models.DateField()),
                ('next_appointment_date', models.DateField()),
                ('gender', models.CharField(max_length=150)),
                ('community', models.CharField(blank=True, max_length=500, null=True)),
                ('pregnant', models.CharField(default='NAO', max_length=10)),
                ('brestfeeding', models.CharField(default='NAO', max_length=10)),
                ('tb', models.CharField(default='NAO', max_length=10)),
                ('synced', models.BooleanField(default=False)),
            ],
        ),
    ]
