# Generated by Django 3.2.19 on 2023-06-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230526_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missedappointment',
            name='patient_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patienteligiblevlcollection',
            name='patient_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='viralloadtestresult',
            name='patient_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='patient_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
