# Generated by Django 3.2.23 on 2024-02-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_activeindrugmissedappointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeindrugmissedappointment',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
