# Generated by Django 3.2.19 on 2023-05-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_databaseconfig_globalproperty_missedappointment_patienteligiblevlcollection_viralloadtestresult_visi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienteligiblevlcollection',
            name='synced',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
