# Generated by Django 3.2.19 on 2023-05-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_patienteligiblevlcollection_synced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienteligiblevlcollection',
            name='community',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patienteligiblevlcollection',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patienteligiblevlcollection',
            name='health_facility',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patienteligiblevlcollection',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patienteligiblevlcollection',
            name='province',
            field=models.CharField(max_length=255),
        ),
    ]
