# Generated by Django 3.2.23 on 2024-02-29 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_activeindrugmissedappointment_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeindrugmissedappointment',
            name='phone_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='missedappointment',
            name='phone_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patienteligiblevlcollection',
            name='phone_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='viralloadtestresult',
            name='phone_number',
            field=models.TextField(blank=True, null=True),
        ),
    ]
