# Generated by Django 3.2.19 on 2023-07-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230601_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienteligiblevlcollection',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='viralloadtestresult',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
