# Generated by Django 3.2.19 on 2023-05-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20230519_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarcadosLevantamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=150)),
                ('district', models.CharField(blank=True, max_length=150, null=True)),
                ('health_facility', models.CharField(max_length=150)),
                ('patient_id', models.IntegerField()),
                ('patient_name', models.CharField(max_length=255)),
                ('patient_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.IntegerField()),
                ('phone_number', models.CharField(blank=True, max_length=150, null=True)),
                ('appointment_date', models.DateField()),
                ('next_appointment_date', models.DateField()),
                ('gender', models.CharField(max_length=150)),
                ('community', models.CharField(blank=True, max_length=500, null=True)),
                ('pregnant', models.CharField(default='NAO', max_length=10)),
                ('breastfeeding', models.CharField(default='NAO', max_length=10)),
                ('tb', models.CharField(default='NAO', max_length=10)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PacientesCargaAlta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=255)),
                ('district', models.CharField(blank=True, max_length=255, null=True)),
                ('community', models.CharField(blank=True, max_length=255, null=True)),
                ('health_facility', models.CharField(blank=True, max_length=255, null=True)),
                ('patient_id', models.IntegerField()),
                ('patient_name', models.CharField(max_length=255)),
                ('patient_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.IntegerField()),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('pregnant', models.CharField(blank=True, default='NAO', max_length=10, null=True)),
                ('last_vl_date', models.DateTimeField(blank=True, null=True)),
                ('last_vl_value', models.CharField(blank=True, max_length=100, null=True)),
                ('last_vl_quality', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Patient Eligible for VL Collection',
                'verbose_name_plural': 'Patients Eligible for VL Collection',
            },
        ),
        migrations.RenameField(
            model_name='elegiveiscv',
            old_name='name',
            new_name='community',
        ),
        migrations.RenameField(
            model_name='visit',
            old_name='brestfeeding',
            new_name='breastfeeding',
        ),
        migrations.RemoveField(
            model_name='elegiveiscv',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='elegiveiscv',
            name='nid',
        ),
        migrations.RemoveField(
            model_name='elegiveiscv',
            name='phone',
        ),
        migrations.AddField(
            model_name='elegiveiscv',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='elegiveiscv',
            name='last_vl_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='elegiveiscv',
            name='last_vl_quality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='elegiveiscv',
            name='last_vl_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='elegiveiscv',
            name='patient_identifier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='elegiveiscv',
            name='patient_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='elegiveiscv',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='elegiveiscv',
            name='pregnant',
            field=models.CharField(blank=True, default='NAO', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='elegiveiscv',
            name='province',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='elegiveiscv',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patienteligiblevlcollection',
            name='synced',
            field=models.BooleanField(default=False),
        ),
    ]
