# Generated by Django 3.2.19 on 2023-09-20 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20230920_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='district',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='gender',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='visit',
            name='patient_identifier',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='patient_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='phone_number',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='province',
            field=models.CharField(max_length=500),
        ),
    ]
