# Generated by Django 3.2.19 on 2023-05-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20230519_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elegiveiscv',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='marcadoslevantamento',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pacientescargaalta',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
