# Generated by Django 3.2.19 on 2023-09-22 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20230920_0552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='phone_number',
        ),
    ]
