# Generated by Django 3.2.19 on 2023-05-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20230519_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elegiveiscv',
            name='created_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='marcadoslevantamento',
            name='appointment_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='marcadoslevantamento',
            name='created_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='marcadoslevantamento',
            name='next_appointment_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='pacientescargaalta',
            name='created_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='visit',
            name='appointment_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='visit',
            name='next_appointment_date',
            field=models.DateTimeField(),
        ),
    ]
