# Generated by Django 3.2.19 on 2023-09-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_visit_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='phone_number',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
