# Generated by Django 3.2.19 on 2023-05-20 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20230520_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elegiveiscv',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='marcadoslevantamento',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='missedappointment',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='pacientescargaalta',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='patienteligiblevlcollection',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='viralloadtestresult',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='patient_id',
        ),
    ]
