# Generated by Django 3.2.19 on 2023-09-22 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_visit_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='phone_number',
            field=models.TextField(blank=True, null=True),
        ),
    ]
